### ISSUE TITLE
SemanticVersion no longer works in pip 6.0+

### ISSUE THREAD

**Issue by birdsoaf** [gae-init/gae-init#292]
```shell
Traceback (most recent call last):
  File "./run.py", line 658, in <module>
    run()
  File "./run.py", line 639, in run
    print_out_update()
  File "./run.py", line 421, in print_out_update
    SemVer = pip._vendor.distlib.version.SemanticVersion
AttributeError: 'module' object has no attribute 'version'
```

**Comment by birdsoaf** [comment]
Pip changed a bit, the SemanticVersion class is located in a new spot. 
```
 import pip._vendor.distlib.version
 SemVer = pip._vendor.distlib.version.SemanticVersion
```

**Comment by lipis** [comment]
Should be OK now..

**Comment by birdsoaf** [comment]
This is still broken. Maybe this?

```
  try:
    import pip
    SemVer = pip.util.version.SemanticVersion
  except AttributeError:
    import pip._vendor.distlib.version
    SemVer = pip._vendor.distlib.version.SemanticVersion
```

**Comment by lipis** [comment]
Very weird.. but it looks like it fixes it..
will update
