### ISSUE TITLE
ImportError: cannot import name py31compat

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#1157]
I'm trying to run gae-init on a new machine and getting this error

```
ERROR    2019-05-18 19:17:02,706 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/lipis/work/lipis/gae-init/init/main/main.py", line 27, in <module>
    import control
  File "/Users/lipis/work/lipis/gae-init/init/main/control/__init__.py", line 9, in <module>
    from .test import *
  File "/Users/lipis/work/lipis/gae-init/init/main/control/test.py", line 9, in <module>
    import versions
  File "/Users/lipis/work/lipis/gae-init/init/main/control/versions.py", line 4, in <module>
    import pkg_resources
  File "lib/pkg_resources/__init__.py", line 959, in <module>
    class Environment:
  File "lib/pkg_resources/__init__.py", line 963, in Environment
    self, search_path=None, platform=get_supported_platform(),
  File "lib/pkg_resources/__init__.py", line 190, in get_supported_platform
    plat = get_build_platform()
  File "lib/pkg_resources/__init__.py", line 398, in get_build_platform
    version = _macosx_vers()
  File "lib/pkg_resources/__init__.py", line 369, in _macosx_vers
    version = platform.mac_ver()[0]
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.py", line 797, in mac_ver
    info = _mac_ver_xml()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.py", line 774, in _mac_ver_xml
    pl = plistlib.readPlist(fn)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 75, in readPlist
    pathOrFile = open(pathOrFile)
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/stubs.py", line 283, in __init__
    raise IOError(errno.EACCES, 'file not accessible', filename)
IOError: [Errno 13] file not accessible: '/System/Library/CoreServices/SystemVersion.plist'
INFO     2019-05-18 19:17:02,712 module.py:861] default: "GET /_ah/warmup HTTP/1.1" 500 749
ERROR    2019-05-18 19:17:02,798 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/lipis/work/lipis/gae-init/init/main/main.py", line 27, in <module>
    import control
  File "/Users/lipis/work/lipis/gae-init/init/main/control/__init__.py", line 9, in <module>
    from .test import *
  File "/Users/lipis/work/lipis/gae-init/init/main/control/test.py", line 9, in <module>
    import versions
  File "/Users/lipis/work/lipis/gae-init/init/main/control/versions.py", line 4, in <module>
    import pkg_resources
  File "lib/pkg_resources/__init__.py", line 79, in <module>
    from . import py31compat
ImportError: cannot import name py31compat
```

**Comment by gmist** [comment]
Cloud SDK version?

**Comment by lipis** [comment]
240.0.0 and 246.0.0

Python 2.7.16

**Comment by gmist** [comment]
This is strange because when I creating a project from scratch ```py31compat.py```  is exist  in the directory ```lib/pkg_resources```.

**Comment by supern8ent** [comment]
I haven't seen the lib.zip thing working for quite some time.
Currently we do `sys_path_insert('lib')` instead of
`sys_path_insert('lib.zip')` in `appengine_config.py` and comment out the
line ` - ^lib/.*` in `app.yaml`.

**Comment by lipis** [comment]
Works with `237.0.0` and there are some issues that already reported here: 
- https://issuetracker.google.com/issues/132240370
- https://stackoverflow.com/questions/55151062/gcloud-update-broke-my-app-gcp-python-2-7

**Comment by lipis** [comment]
@supern8ent try running it with 237 and see if the zip file is working there..

**Comment by lipis** [comment]
@gmist are you sure it works with the latest version?

I'm getting this error first:

```bash
[Browsersync] Reloading Browsers...
INFO     2019-05-29 21:11:41,730 devappserver2.py:278] Skipping SDK update check.
WARNING  2019-05-29 21:11:41,997 simple_search_stub.py:1196] Could not read search indexes from temp/storage/search_indexes
INFO     2019-05-29 21:11:41,999 api_server.py:275] Starting API server at: http://localhost:63559
INFO     2019-05-29 21:11:42,159 dispatcher.py:256] Starting module "default" running at: http://127.0.0.1:8080
INFO     2019-05-29 21:11:42,163 admin_server.py:150] Starting admin server at: http://localhost:8081
INFO     2019-05-29 21:11:44,536 instance.py:294] Instance PID: 64319
ERROR    2019-05-29 21:11:45,768 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/lipis/work/lipis/gae-init/init/main/main.py", line 29, in <module>
    import control
  File "/Users/lipis/work/lipis/gae-init/init/main/control/__init__.py", line 9, in <module>
    from .test import *
  File "/Users/lipis/work/lipis/gae-init/init/main/control/test.py", line 9, in <module>
    import versions
  File "/Users/lipis/work/lipis/gae-init/init/main/control/versions.py", line 4, in <module>
    import pkg_resources
  File "lib/pkg_resources/__init__.py", line 959, in <module>
    class Environment:
  File "lib/pkg_resources/__init__.py", line 963, in Environment
    self, search_path=None, platform=get_supported_platform(),
  File "lib/pkg_resources/__init__.py", line 190, in get_supported_platform
    plat = get_build_platform()
  File "lib/pkg_resources/__init__.py", line 398, in get_build_platform
    version = _macosx_vers()
  File "lib/pkg_resources/__init__.py", line 369, in _macosx_vers
    version = platform.mac_ver()[0]
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.py", line 797, in mac_ver
    info = _mac_ver_xml()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.py", line 774, in _mac_ver_xml
    pl = plistlib.readPlist(fn)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 75, in readPlist
    pathOrFile = open(pathOrFile)
  File "/Users/lipis/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/stubs.py", line 283, in __init__
    raise IOError(errno.EACCES, 'file not accessible', filename)
IOError: [Errno 13] file not accessible: '/System/Library/CoreServices/SystemVersion.plist'
INFO     2019-05-29 21:11:45,783 module.py:861] default: "GET /_ah/warmup HTTP/1.1" 500 749
```

**Comment by lipis** [comment]
Everything is OK when downgrading to 237..

**Comment by lipis** [comment]
Works now..
